# Generated by Django 4.0.1 on 2022-01-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='descrition',
            new_name='description',
        ),
    ]
